# Generated by Django 4.2.11 on 2024-04-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_joined_date_member_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
